/* GENERATED from demo-reference.html by tools/gen-app-data.mjs — edit the demo, then regenerate. */
import type {Sub, Cat} from './types';

/* category tints */
export const C: Record<Cat,string> = {"nic":"#8FA3BF","caf":"#C9996B","alc":"#C97F8C","can":"#93AE84","psy":"#A594D4","stim":"#DE8A6A","rx":"#7FB2C4","dep":"#8C93CC","benzo":"#6E9BD8","opi":"#CB7FB5","oth":"#8B98A5"};

/* SUBSTANCE CATALOGUE — language-neutral PK records (names/notes live in i18n).
   tp = time-to-peak (min), hl = half-life (min), dur = acute window (min),
   ev = evidence strength A/B/C. Every value is a population average. NO dosing data. */
export const SUBS: Sub[] = [
  {"id":"cig","c":"nic","i":"cig","u":"unit","kind":"std","tp":9,"hl":120,"dur":35,"ev":"A","s":["reg","thin","rolled"]},
  {"id":"vape","c":"nic","i":"vape","u":"session","kind":"std","tp":6,"hl":110,"dur":35,"ev":"B","s":["disp","pod","liquid"]},
  {"id":"hook","c":"nic","i":"hookah","u":"session","kind":"std","tp":25,"hl":120,"dur":60,"ev":"C","s":["reg","nonic"]},
  {"id":"pouch","c":"nic","i":"pill","u":"unit","kind":"std","tp":30,"hl":120,"dur":45,"ev":"B","s":["3mg","6mg","9mg"]},
  {"id":"snus","c":"nic","i":"pill","u":"unit","kind":"std","tp":30,"hl":120,"dur":45,"ev":"B","s":[]},
  {"id":"ngum","c":"nic","i":"gum","u":"unit","kind":"std","tp":30,"hl":120,"dur":45,"ev":"A","s":[]},
  {"id":"cigar","c":"nic","i":"cigar","u":"unit","kind":"std","tp":20,"hl":120,"dur":60,"ev":"B","s":["cigarillo","cigar"]},
  {"id":"htp","c":"nic","i":"vape","u":"unit","kind":"std","tp":7,"hl":120,"dur":35,"ev":"B","s":[]},
  {"id":"cof","c":"caf","i":"cup","u":"cup","kind":"std","tp":45,"hl":300,"dur":240,"ev":"A","s":["espresso","latte","black","instant"]},
  {"id":"tea","c":"caf","i":"tea","u":"cup","kind":"std","tp":40,"hl":280,"dur":180,"ev":"B","s":["black","green","matcha"]},
  {"id":"nrg","c":"caf","i":"can","u":"can","kind":"std","tp":45,"hl":300,"dur":240,"ev":"A","s":["small","large","shot"]},
  {"id":"cola","c":"caf","i":"can","u":"cup","kind":"std","tp":45,"hl":300,"dur":120,"ev":"B","s":["reg","zero"]},
  {"id":"mate","c":"caf","i":"tea","u":"cup","kind":"std","tp":45,"hl":300,"dur":180,"ev":"B","s":[]},
  {"id":"cafp","c":"caf","i":"tablet","u":"tab","kind":"std","tp":45,"hl":300,"dur":300,"ev":"A","s":[]},
  {"id":"alc","c":"alc","i":"glass","u":"dose","kind":"zero","tp":35,"rate":1,"dur":90,"ev":"A","s":["beer","wine","shot","cocktail"]},
  {"id":"can","c":"can","i":"leaf","u":"time","kind":"std","tp":10,"hl":120,"dur":180,"ev":"B","s":["joint","vape","bong","edible","dab"],"editSub":"edible"},
  {"id":"hash","c":"can","i":"leaf","u":"time","kind":"std","tp":10,"hl":120,"dur":180,"ev":"B","s":["joint","bong","edible"],"editSub":"edible"},
  {"id":"synth","c":"can","i":"leaf","u":"hit","kind":"std","tp":10,"hl":60,"dur":120,"ev":"C","s":[]},
  {"id":"cbd","c":"can","i":"drop","u":"dose","kind":"std","tp":90,"hl":1200,"dur":360,"ev":"C","s":["oil","caps","flower"]},
  {"id":"lsd","c":"psy","i":"blot","u":"dose","kind":"std","tp":120,"hl":210,"dur":540,"ev":"B","s":["blotter","liquid","quarter","analog"]},
  {"id":"psi","c":"psy","i":"shroom","u":"gram","kind":"std","tp":120,"hl":150,"dur":360,"ev":"B","s":["dry","fresh","tea","truffles"]},
  {"id":"2cb","c":"psy","i":"blot","u":"dose","kind":"std","tp":90,"hl":120,"dur":300,"ev":"C","s":["tab","powder"]},
  {"id":"dmt","c":"psy","i":"eye","u":"hit","kind":"std","tp":3,"hl":15,"dur":15,"ev":"B","s":["smoked","vape"]},
  {"id":"5meo","c":"psy","i":"eye","u":"hit","kind":"std","tp":3,"hl":12,"dur":20,"ev":"C","s":[]},
  {"id":"aya","c":"psy","i":"cup","u":"cup","kind":"std","tp":90,"hl":90,"dur":240,"ev":"C","s":[]},
  {"id":"mesc","c":"psy","i":"cactus","u":"dose","kind":"std","tp":150,"hl":360,"dur":600,"ev":"C","s":["sanpedro","peyote","synthetic"]},
  {"id":"salv","c":"psy","i":"leaf","u":"hit","kind":"std","tp":2,"hl":8,"dur":15,"ev":"C","s":[]},
  {"id":"mdma","c":"stim","i":"gem","u":"mg","kind":"std","tp":120,"hl":510,"dur":300,"ev":"B","step":25,"def":75,"nonlinear":true,"s":["capsule","crystal","half"]},
  {"id":"coc","c":"stim","i":"mound","u":"unit","kind":"std","tp":20,"hl":75,"dur":75,"ev":"A","s":["line","bump"]},
  {"id":"crack","c":"stim","i":"mound","u":"hit","kind":"std","tp":5,"hl":60,"dur":20,"ev":"B","s":[]},
  {"id":"amph","c":"stim","i":"caps","u":"tab","kind":"std","tp":180,"hl":600,"dur":420,"ev":"A","s":["attent","vyvanse"]},
  {"id":"speed","c":"stim","i":"bolt","u":"dose","kind":"std","tp":45,"hl":600,"dur":360,"ev":"B","s":["snorted","oral"]},
  {"id":"meth","c":"stim","i":"bolt","u":"dose","kind":"std","tp":30,"hl":600,"dur":480,"ev":"B","s":["smoked","snorted","oral"]},
  {"id":"cath","c":"stim","i":"spark","u":"dose","kind":"std","tp":45,"hl":130,"dur":150,"ev":"C","s":["4mmc","3mmc","apvp","other"]},
  {"id":"khat","c":"stim","i":"leaf","u":"session","kind":"std","tp":120,"hl":190,"dur":180,"ev":"C","s":[]},
  {"id":"ket","c":"dep","i":"vial","u":"mg","kind":"std","tp":22,"hl":180,"dur":55,"ev":"A","step":10,"def":40,"s":["powder","liquid"]},
  {"id":"ghb","c":"dep","i":"drop","u":"dose","kind":"std","tp":45,"hl":40,"dur":120,"ev":"A","s":["ghb","gbl"]},
  {"id":"preg","c":"dep","i":"caps","u":"tab","kind":"std","tp":90,"hl":380,"dur":480,"ev":"A","s":[]},
  {"id":"n2o","c":"oth","i":"balloon","u":"balloon","kind":"std","tp":1,"hl":3,"dur":3,"ev":"B","s":[]},
  {"id":"popp","c":"oth","i":"bottle","u":"hit","kind":"std","tp":1,"hl":2,"dur":5,"ev":"B","s":[]},
  {"id":"dxm","c":"oth","i":"bottle","u":"dose","kind":"std","tp":150,"hl":240,"dur":360,"ev":"B","s":["syrup","tab"]},
  {"id":"krat","c":"oth","i":"leaf","u":"dose","kind":"std","tp":60,"hl":200,"dur":240,"ev":"C","s":["powder","tea","caps"]},
  {"id":"alpr","c":"benzo","i":"tablet","u":"tab","kind":"std","tp":90,"hl":660,"dur":300,"ev":"A","s":[]},
  {"id":"clon","c":"benzo","i":"tablet","u":"tab","kind":"std","tp":120,"hl":1800,"dur":480,"ev":"A","s":[]},
  {"id":"diaz","c":"benzo","i":"tablet","u":"tab","kind":"std","tp":60,"hl":2400,"dur":480,"ev":"A","s":[]},
  {"id":"lora","c":"benzo","i":"tablet","u":"tab","kind":"std","tp":120,"hl":720,"dur":420,"ev":"A","s":[]},
  {"id":"brot","c":"benzo","i":"tablet","u":"tab","kind":"std","tp":60,"hl":300,"dur":360,"ev":"B","s":[]},
  {"id":"zolp","c":"benzo","i":"moon","u":"tab","kind":"std","tp":60,"hl":150,"dur":300,"ev":"A","s":[]},
  {"id":"oxy","c":"opi","i":"tablet","u":"tab","kind":"std","tp":60,"hl":210,"dur":300,"ev":"A","s":["ir","er"]},
  {"id":"tram","c":"opi","i":"tablet","u":"tab","kind":"std","tp":120,"hl":360,"dur":360,"ev":"A","s":[]},
  {"id":"cod","c":"opi","i":"tablet","u":"tab","kind":"std","tp":60,"hl":180,"dur":270,"ev":"A","s":["tab","syrup"]},
  {"id":"her","c":"opi","i":"mound","u":"dose","kind":"std","tp":15,"hl":180,"dur":240,"ev":"B","s":["smoked","snorted","injected"]},
  {"id":"fent","c":"opi","i":"drop","u":"dose","kind":"std","tp":5,"hl":220,"dur":60,"ev":"B","s":[]},
  {"id":"bupr","c":"opi","i":"pulse","u":"tab","kind":"chronic","tp":90,"hl":2000,"dur":0,"ev":"A","s":["subutex","suboxone"]},
  {"id":"mdone","c":"opi","i":"pulse","u":"dose","kind":"chronic","tp":180,"hl":1500,"dur":0,"ev":"A","s":[]},
  {"id":"mph","c":"rx","i":"pill","u":"mg","kind":"std","tp":90,"hl":180,"dur":210,"ev":"A","step":10,"def":10,"s":["mg10","mg20","la"],"editSub":"la"},
  {"id":"anlg","c":"rx","i":"pill","u":"unit","kind":"std","tp":45,"hl":150,"dur":270,"ev":"A","s":["tab","focus"]},
  {"id":"ibu","c":"rx","i":"pill","u":"tab","kind":"std","tp":90,"hl":120,"dur":360,"ev":"A","s":[]},
  {"id":"dipy","c":"rx","i":"pill","u":"tab","kind":"std","tp":90,"hl":160,"dur":300,"ev":"A","s":[]},
  {"id":"mela","c":"rx","i":"moon","u":"mg","kind":"std","tp":50,"hl":50,"dur":120,"ev":"A","step":1,"def":3,"s":["1","3","5"]},
  {"id":"sild","c":"rx","i":"pill","u":"tab","kind":"std","tp":60,"hl":240,"dur":240,"ev":"A","s":[]},
  {"id":"pse","c":"rx","i":"pill","u":"tab","kind":"std","tp":120,"hl":360,"dur":300,"ev":"A","s":[]},
  {"id":"moda","c":"rx","i":"pill","u":"tab","kind":"std","tp":150,"hl":780,"dur":600,"ev":"A","s":[]},
  {"id":"quet","c":"rx","i":"pill","u":"tab","kind":"std","tp":90,"hl":420,"dur":480,"ev":"A","s":[]},
  {"id":"ssri","c":"rx","i":"pulse","u":"mg","kind":"chronic","tp":300,"hl":1600,"dur":0,"ev":"A","step":5,"def":10,"s":["escit","sert","fluox"]},
  {"id":"snri","c":"rx","i":"pulse","u":"tab","kind":"chronic","tp":300,"hl":700,"dur":0,"ev":"A","s":["venla","dulox"]},
  {"id":"maoi","c":"rx","i":"pulse","u":"tab","kind":"chronic","tp":120,"hl":600,"dur":0,"ev":"A","s":[]},
  {"id":"lith","c":"rx","i":"pulse","u":"tab","kind":"chronic","tp":120,"hl":1440,"dur":0,"ev":"A","s":[]},
];
