/* GENERATED from demo-reference.html parts by scratchpad/gen-ts.mjs — edit the demo, not this file. */
import type {Cat, Sev} from './types';

/* explicit pairs: [idA, idB, severity, textKey] */
export const RISK: [string,string,Sev,string][] = [
  ["alc","coc","unsafe","alc_coc"],
  ["alc","ket","danger","alc_ket"],
  ["alc","mela","caution","alc_mela"],
  ["alc","can","caution","alc_can"],
  ["alc","anlg","unsafe","alc_anlg"],
  ["alc","ibu","caution","alc_nsaid"],
  ["alc","dipy","caution","alc_nsaid"],
  ["alc","ghb","danger","alc_ghb"],
  ["alc","popp","caution","alc_popp"],
  ["alc","n2o","caution","alc_n2o"],
  ["alc","preg","unsafe","alc_preg"],
  ["alc","dxm","unsafe","alc_dxm"],
  ["alc","quet","unsafe","alc_quet"],
  ["alc","krat","unsafe","alc_krat"],
  ["mdma","ssri","caution","mdma_ssri"],
  ["mdma","snri","caution","mdma_ssri"],
  ["mdma","coc","unsafe","mdma_coc"],
  ["mdma","alc","unsafe","mdma_alc"],
  ["mdma","lith","caution","mdma_lith"],
  ["mdma","tram","unsafe","sero_sero"],
  ["mdma","dxm","unsafe","sero_sero"],
  ["coc","mph","unsafe","coc_mph"],
  ["lsd","ssri","caution","psy_ssri"],
  ["psi","ssri","caution","psy_ssri"],
  ["2cb","ssri","caution","psy_ssri"],
  ["ghb","ket","danger","ghb_ket"],
  ["ghb","n2o","unsafe","ghb_n2o"],
  ["ket","n2o","caution","ket_n2o"],
  ["ket","preg","unsafe","ket_preg"],
  ["popp","sild","danger","popp_sild"],
  ["tram","ssri","unsafe","sero_sero"],
  ["tram","snri","unsafe","sero_sero"],
  ["tram","maoi","danger","maoi_sero"],
  ["tram","aya","danger","maoi_sero"],
  ["tram","lith","caution","tram_lith"],
  ["dxm","ssri","unsafe","sero_sero"],
  ["dxm","snri","unsafe","sero_sero"],
  ["dxm","tram","unsafe","sero_sero"],
  ["dxm","maoi","danger","maoi_sero"],
  ["dxm","aya","danger","maoi_sero"],
  ["maoi","ssri","danger","maoi_ssri"],
  ["maoi","snri","danger","maoi_ssri"],
  ["aya","ssri","danger","maoi_ssri"],
  ["aya","snri","danger","maoi_ssri"],
  ["maoi","pse","danger","maoi_pse"],
  ["aya","pse","danger","maoi_pse"],
];

/* one substance against a whole category */
export const IDCAT: [string,Cat,Sev,string][] = [
  ["lith","psy","danger","lith_psy"],
  ["maoi","stim","danger","maoi_stim"],
  ["aya","stim","danger","maoi_stim"],
  ["maoi","psy","caution","maoi_psy"],
  ["aya","psy","caution","maoi_psy"],
  ["mph","stim","unsafe","stim_stim"],
  ["mph","caf","caution","stim_caf"],
  ["tram","stim","unsafe","tram_stim"],
  ["popp","stim","caution","popp_stim"],
  ["sild","stim","caution","sild_stim"],
  ["n2o","opi","unsafe","n2o_opi"],
  ["n2o","benzo","caution","n2o_benzo"],
  ["preg","benzo","unsafe","preg_benzo"],
  ["preg","opi","danger","preg_opi"],
  ["dxm","opi","unsafe","dxm_opi"],
  ["dxm","benzo","caution","dxm_benzo"],
  ["dxm","stim","caution","dxm_stim"],
  ["quet","benzo","caution","sed_benzo"],
  ["quet","opi","unsafe","sed_opi"],
  ["mela","benzo","caution","sed_benzo"],
  ["krat","opi","danger","krat_opi"],
  ["krat","benzo","unsafe","krat_benzo"],
  ["moda","stim","caution","stim_caf"],
  ["pse","stim","caution","pse_stim"],
];

/* category against category — the safety net */
export const CATRISK: [Cat,Cat,Sev,string][] = [
  ["stim","stim","unsafe","stim_stim"],
  ["stim","caf","caution","stim_caf"],
  ["stim","psy","caution","stim_psy"],
  ["stim","can","caution","stim_can"],
  ["stim","alc","caution","stim_alc"],
  ["stim","opi","unsafe","stim_opi"],
  ["stim","benzo","caution","stim_benzo"],
  ["psy","psy","caution","psy_psy"],
  ["psy","can","caution","psy_can"],
  ["psy","alc","caution","psy_alc"],
  ["dep","dep","danger","dep_dep"],
  ["dep","alc","danger","dep_alc"],
  ["dep","benzo","danger","dep_benzo"],
  ["dep","opi","danger","dep_opi"],
  ["benzo","alc","danger","benzo_alc"],
  ["benzo","opi","danger","benzo_opi"],
  ["benzo","benzo","unsafe","benzo_benzo"],
  ["benzo","can","caution","benzo_can"],
  ["opi","alc","danger","opi_alc"],
  ["opi","opi","danger","opi_opi"],
  ["opi","can","caution","opi_can"],
  ["nic","nic","caution","nic_nic"],
  ["caf","caf","caution","caf_caf"],
];

/* meds typed into the profile that create standing risks (substring match) */
export const MED_FLAGS: {kw:string[]; hitsCat:Cat[]; sev:Sev; k:string}[] = [
  {"kw":["ליתיום","lithium","licarbium","ליקרביום"],"hitsCat":["psy"],"sev":"danger","k":"lith_psy"},
  {"kw":["maoi","מאוי","נרדיל","nardil","parnate","פרנייט","moclobemide","מוקלובמיד","selegiline","סלגילין"],"hitsCat":["stim"],"sev":"danger","k":"maoi_stim"},
  {"kw":["אסציטלופרם","סרטלין","סרטרלין","פלואוקסטין","ssri","snri","ציפרלקס","לוסטרל","פרוזק","cipralex","lustral","prozac","escitalopram","sertraline","fluoxetine","paroxetine","פרוקסטין","סרוקסט","seroxat","venlafaxine","ונלפקסין","אפקסור","effexor","duloxetine","דולוקסטין","סימבלטה","cymbalta","fluvoxamine","פבוקסיל"],"hitsCat":["stim"],"sev":"caution","k":"ssri_stim"},
  {"kw":["טרמדול","tramadol","טרמדקס","tramadex","זלדיאר","zaldiar"],"hitsCat":["stim","psy"],"sev":"unsafe","k":"tram_sero"},
  {"kw":["קלונקס","clonex","clonazepam","קלונאזפאם","קסנקס","xanax","alprazolam","אלפרזולם","ואבן","vaben","ואליום","valium","diazepam","דיאזפאם","לוריבן","lorivan","lorazepam","לוראזפאם","בונדורמין","bondormin","brotizolam","סטילנוקס","stilnox","zolpidem","זולפידם","אמביאן","ambien","נוקטורנו","nocturno","zopiclone","אימובן","imovane","oxazepam"],"hitsCat":["alc","opi","dep"],"sev":"danger","k":"benzo_dep"},
  {"kw":["oxycodone","אוקסיקודון","percocet","פרקוסט","oxycontin","אוקסיקונטין","targin","טרגין","methadone","מתדון","buprenorphine","בופרנורפין","subutex","סובוטקס","suboxone","סובוקסון","fentanyl","פנטניל","codeine","קודאין","morphine","מורפין","זמדול","zamadol"],"hitsCat":["alc","benzo","dep"],"sev":"danger","k":"opi_dep"},
  {"kw":["pregabalin","פרגבלין","lyrica","ליריקה","gabapentin","גבפנטין","neurontin"],"hitsCat":["opi","benzo","alc"],"sev":"unsafe","k":"preg_dep"},
  {"kw":["quetiapine","קווטיאפין","seroquel","סרוקוול","olanzapine","אולנזפין","זיפרקסה","zyprexa"],"hitsCat":["alc","benzo","opi"],"sev":"caution","k":"sed_dep"},
];

export const RESOURCES: {id:string; tel:string; href:string}[] = [{"id":"mda","tel":"101","href":"tel:101"},{"id":"eran","tel":"1201","href":"tel:1201"},{"id":"alsam","tel":"","href":"https://alsam.org.il"},{"id":"shore","tel":"","href":"https://safeshore.org.il"}];
